language: php
sudo: required
php:
  - '7.2'
env:
  DOCKER_COMPOSE_VERSION: 1.18.0
services:
  - docker

before_script:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - composer install
  - docker-compose up -d
  - docker exec -it cqrs-blog-php php bin/console doctrine:database:create
  - docker exec -it cqrs-blog-php php bin/console doctrine:database:create --env=test
  - docker exec -it cqrs-blog-php php bin/console doctrine:schema:create
  - docker exec -it cqrs-blog-php php bin/console doctrine:schema:create --env=test
  - docker exec -it cqrs-blog-php php bin/console d:m:m --env=test
  - docker exec -it cqrs-blog-php php bin/console d:m:m

script:
  - docker exec -it cqrs-blog-php APP_DEV=test vendor/bin/behat
  - docker exec -it cqrs-blog-php APP_DEV=test vendor/bin/phpspec run