# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: cqrs-blog-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
      - php
      - redis
  php:
    build: ./docker/php
    container_name: cqrs-blog-php
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cqrs-blog-phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: test
    restart: always
    ports:
     - 8000:80
    volumes:
     - /sessions

  redis:
    image: redis
    container_name: cqrs-blog-redis
    ports:
      - 6379:6379